from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from scripts.rag import answer_question


REPORT_PATH = PROJECT_ROOT / "docs" / "evaluation_report.md"

TEST_CASES = [
    {
        "question": "Which professor is most often described as making difficult CS concepts easier to understand?",
        "ground_truth": "The answer must cite retrieved review evidence about clarity, explanation, concepts, or understanding.",
    },
    {
        "question": "Which professor has reviews mentioning very hard exams or tough grading?",
        "ground_truth": "The answer must cite retrieved evidence about exams, quizzes, grading, hard, tough, or difficult.",
    },
    {
        "question": "Which professor has reviews that mention disorganization or poor structure?",
        "ground_truth": "The answer must cite retrieved evidence about disorganization, confusing structure, unclear course flow, or poor organization.",
    },
    {
        "question": "Which professor has mixed or polarized reviews?",
        "ground_truth": "The answer must identify professors only when retrieved evidence shows both positive and negative review signals.",
    },
    {
        "question": "Which professor has reviews recommending office hours?",
        "ground_truth": "The answer must cite retrieved evidence about office hours, helpfulness, availability, email, or asking questions.",
    },
]


def source_list(chunks: list[dict]) -> str:
    sources = []
    for chunk in chunks:
        metadata = chunk["metadata"]
        sources.append(f"{metadata['source_file']} chunk {metadata['chunk_number']}/{metadata['total_chunks']}")
    return "; ".join(sources)


def build_report(rows: list[dict], failure_note: str) -> str:
    lines = [
        "# Evaluation Report",
        "",
        "The evaluation uses five domain questions against the processed GMU CS professor review corpus. Accuracy labels should be checked manually after reading the generated answer and retrieved chunks.",
        "",
        "| # | Question | Ground-truth answer | Generated system answer | Retrieved chunks | Retrieved source files | Retrieval accuracy | Response accuracy | Notes |",
        "|---|----------|---------------------|-------------------------|------------------|------------------------|--------------------|-------------------|-------|",
    ]
    for index, row in enumerate(rows, start=1):
        lines.append(
            "| {index} | {question} | {ground_truth} | {answer} | {chunks} | {sources} | {retrieval_accuracy} | {response_accuracy} | {notes} |".format(
                index=index,
                question=row["question"].replace("|", "\\|"),
                ground_truth=row["ground_truth"].replace("|", "\\|"),
                answer=row["answer"].replace("\n", "<br>").replace("|", "\\|"),
                chunks=row["chunks"].replace("|", "\\|"),
                sources=row["sources"].replace("|", "\\|"),
                retrieval_accuracy=row["retrieval_accuracy"],
                response_accuracy=row["response_accuracy"],
                notes=row["notes"].replace("|", "\\|"),
            )
        )
    lines.extend(
        [
            "",
            "## Failure Case",
            "",
            failure_note,
            "",
            "## How To Interpret The Labels",
            "",
            "- Retrieval accuracy is accurate when the top chunks contain direct evidence for the question.",
            "- Retrieval accuracy is partially accurate when some evidence is present but important professor comparisons are missing.",
            "- Response accuracy is accurate when the answer stays grounded, cites sources, and matches the retrieved evidence.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    rows = []
    try:
        for case in TEST_CASES:
            result = answer_question(case["question"])
            sources = sorted({chunk["metadata"]["source_file"] for chunk in result["chunks"]})
            rows.append(
                {
                    "question": case["question"],
                    "ground_truth": case["ground_truth"],
                    "answer": result["answer"],
                    "chunks": source_list(result["chunks"]),
                    "sources": ", ".join(sources),
                    "retrieval_accuracy": "manual check required",
                    "response_accuracy": "manual check required",
                    "notes": "Generated by scripts/evaluate.py; review the retrieved chunks before final grading.",
                }
            )
        failure_note = (
            "A likely failure case is a broad comparative question such as 'most beginner-friendly.' "
            "The corpus contains short opinion-heavy reviews, and retrieval may return positive comments "
            "from several professors without enough comparable evidence to rank them confidently."
        )
    except Exception as exc:
        rows = [
            {
                "question": case["question"],
                "ground_truth": case["ground_truth"],
                "answer": "Not generated.",
                "chunks": "Not retrieved.",
                "sources": "Not retrieved.",
                "retrieval_accuracy": "not run",
                "response_accuracy": "not run",
                "notes": str(exc),
            }
            for case in TEST_CASES
        ]
        failure_note = f"Evaluation was not executed end-to-end because setup was incomplete: {exc}"

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(build_report(rows, failure_note), encoding="utf-8")
    print(f"Wrote {REPORT_PATH.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
